/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.sdk;

import com.styra.opa.sdk.utils.HTTPClient;
import com.styra.opa.sdk.utils.RetryConfig;
import java.util.Optional;

class SDKConfiguration {
    public HTTPClient defaultClient;
	  public String serverUrl;
    public int serverIdx = 0;
  	public String language = "java";
  	public String openapiDocVersion = "0.2.0";
  	public String sdkVersion = "0.4.3";
  	public String genVersion = "2.298.2";
  	public String userAgent = "speakeasy-sdk/java 0.4.3 2.298.2 0.2.0 com.styra.opa.sdk";
  	
  	
    public Optional<RetryConfig> retryConfig = Optional.empty();
}
