/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.styra.opa.sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

public enum Explain {
    NOTES("notes"),
    FAILS("fails"),
    FULL("full"),
    DEBUG("debug");

    @JsonValue
    private final String value;

    private Explain(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
