/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.sdk.models.shared;

public class Security {
    // Security not configured but we create this class 
    // to help with SecuritySource references in sdk hook context
}