/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import com.styra.opa.utils.LazySingletonValue;
import com.styra.opa.utils.Utils;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class ExecutePolicyRequestBuilder {

    private ExecutePolicyRequest request;
    private final SDKMethodInterfaces.MethodCallExecutePolicy sdk;

    public ExecutePolicyRequestBuilder(SDKMethodInterfaces.MethodCallExecutePolicy sdk) {
        this.sdk = sdk;
    }

    public ExecutePolicyRequestBuilder request(ExecutePolicyRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public ExecutePolicyResponse call() throws Exception {

        return sdk.executePolicy(
            request);
    }
}
