/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.models.operations;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class SDKMethodInterfaces {

    public interface MethodCallExecutePolicy {
        com.styra.opa.models.operations.ExecutePolicyResponse executePolicy(
            com.styra.opa.models.operations.ExecutePolicyRequest request) throws Exception;
    }


    public interface MethodCallExecutePolicyWithInput {
        com.styra.opa.models.operations.ExecutePolicyWithInputResponse executePolicyWithInput(
            com.styra.opa.models.operations.ExecutePolicyWithInputRequest request) throws Exception;
    }


    public interface MethodCallHealth {
        com.styra.opa.models.operations.HealthResponse health(
            Optional<? extends Boolean> bundles,
            Optional<? extends Boolean> plugins,
            Optional<? extends java.util.List<String>> excludePlugin) throws Exception;
    }

}
