/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa;

import com.styra.opa.utils.HTTPClient;
import com.styra.opa.utils.RetryConfig;
import java.util.Optional;

class SDKConfiguration {
    public HTTPClient defaultClient;
	  public String serverUrl;
    public int serverIdx = 0;
  	public String language = "java";
  	public String openapiDocVersion = "0.2.0";
  	public String sdkVersion = "0.2.1";
  	public String genVersion = "2.280.6";
  	public String userAgent = "speakeasy-sdk/java 0.2.1 2.280.6 0.2.0 com.styra.opa";
  	
  	
    public Optional<RetryConfig> retryConfig = Optional.empty();
}
