/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.styra.opa.utils.DateTimeDeserializer;
import com.styra.opa.utils.DateTimeSerializer;
import java.time.OffsetDateTime;

/**
 * Provenance - Provenance information can be requested on individual API calls and are returned inline with the API response. To obtain provenance information on an API call, specify the `provenance=true` query parameter when executing the API call.
 */

public class Provenance {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("version")
    public String version;

    public Provenance withVersion(String version) {
        this.version = version;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("build_commit")
    public String buildCommit;

    public Provenance withBuildCommit(String buildCommit) {
        this.buildCommit = buildCommit;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("build_timestamp")
    public OffsetDateTime buildTimestamp;

    public Provenance withBuildTimestamp(OffsetDateTime buildTimestamp) {
        this.buildTimestamp = buildTimestamp;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("build_host")
    public String buildHost;

    public Provenance withBuildHost(String buildHost) {
        this.buildHost = buildHost;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bundles")
    public java.util.Map<String, Revision> bundles;

    public Provenance withBundles(java.util.Map<String, Revision> bundles) {
        this.bundles = bundles;
        return this;
    }
    
    public Provenance(){}
}
