/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class Revision {
    @JsonProperty("revision")
    public String revision;

    public Revision withRevision(String revision) {
        this.revision = revision;
        return this;
    }
    
    public Revision(@JsonProperty("revision") String revision) {
        this.revision = revision;
  }
}
