/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ServerError {
    @JsonProperty("code")
    public String code;

    public ServerError withCode(String code) {
        this.code = code;
        return this;
    }
    
    @JsonProperty("message")
    public String message;

    public ServerError withMessage(String message) {
        this.message = message;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("errors")
    public ServerErrorErrors[] errors;

    public ServerError withErrors(ServerErrorErrors[] errors) {
        this.errors = errors;
        return this;
    }
    
    public ServerError(@JsonProperty("code") String code, @JsonProperty("message") String message) {
        this.code = code;
        this.message = message;
  }
}
