/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class SuccessfulPolicyEvaluation {
    /**
     * The base or virtual document referred to by the URL path. If the path is undefined, this key will be omitted.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("result")
    public java.lang.Object result;

    public SuccessfulPolicyEvaluation withResult(java.lang.Object result) {
        this.result = result;
        return this;
    }
    
    /**
     * If query metrics are enabled, this field contains query performance metrics collected during the parse, compile, and evaluation steps.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metrics")
    public java.util.Map<String, java.lang.Object> metrics;

    public SuccessfulPolicyEvaluation withMetrics(java.util.Map<String, java.lang.Object> metrics) {
        this.metrics = metrics;
        return this;
    }
    
    /**
     * If decision logging is enabled, this field contains a string that uniquely identifies the decision. The identifier will be included in the decision log event for this decision. Callers can use the identifier for correlation purposes.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("decision_id")
    public String decisionId;

    public SuccessfulPolicyEvaluation withDecisionId(String decisionId) {
        this.decisionId = decisionId;
        return this;
    }
    
    /**
     * Provenance information can be requested on individual API calls and are returned inline with the API response. To obtain provenance information on an API call, specify the `provenance=true` query parameter when executing the API call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("provenance")
    public Provenance provenance;

    public SuccessfulPolicyEvaluation withProvenance(Provenance provenance) {
        this.provenance = provenance;
        return this;
    }
    
    public SuccessfulPolicyEvaluation(){}
}
