/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ExecutePolicyWithInputRequestBody - The input document
 */

public class ExecutePolicyWithInputRequestBody {
    /**
     * Arbitrary JSON used within your policies by accessing `input`
     */
    @JsonProperty("input")
    public java.util.Map<String, java.lang.Object> input;

    public ExecutePolicyWithInputRequestBody withInput(java.util.Map<String, java.lang.Object> input) {
        this.input = input;
        return this;
    }
    
    public ExecutePolicyWithInputRequestBody(@JsonProperty("input") java.util.Map<String, java.lang.Object> input) {
        this.input = input;
  }
}
