/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ExecutePolicyWithInputResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public ExecutePolicyWithInputResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public ExecutePolicyWithInputResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public ExecutePolicyWithInputResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Success.
     * The server also returns 200 if the path refers to an undefined document. In this case, the response will not contain a result property.
     * 
     */
    
    public com.styra.opa.models.shared.SuccessfulPolicyEvaluation successfulPolicyEvaluation;

    public ExecutePolicyWithInputResponse withSuccessfulPolicyEvaluation(com.styra.opa.models.shared.SuccessfulPolicyEvaluation successfulPolicyEvaluation) {
        this.successfulPolicyEvaluation = successfulPolicyEvaluation;
        return this;
    }
    
    /**
     * Bad Request
     */
    
    public com.styra.opa.models.shared.ClientError clientError;

    public ExecutePolicyWithInputResponse withClientError(com.styra.opa.models.shared.ClientError clientError) {
        this.clientError = clientError;
        return this;
    }
    
    /**
     * Server Error
     */
    
    public com.styra.opa.models.shared.ServerError serverError;

    public ExecutePolicyWithInputResponse withServerError(com.styra.opa.models.shared.ServerError serverError) {
        this.serverError = serverError;
        return this;
    }
    
    
    public java.util.Map<String, String[]> headers;

    public ExecutePolicyWithInputResponse withHeaders(java.util.Map<String, String[]> headers) {
        this.headers = headers;
        return this;
    }
    
    public ExecutePolicyWithInputResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode, @JsonProperty("RawResponse") HttpResponse<byte[]> rawResponse, @JsonProperty("Headers") java.util.Map<String, String[]> headers) {
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.headers = headers;
  }
}
