/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.models.operations;

import com.styra.opa.utils.SpeakeasyMetadata;


public class HealthRequest {
    /**
     * Boolean parameter to account for bundle activation status in response. This includes any discovery bundles or bundles defined in the loaded discovery configuration.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=bundles")
    public Boolean bundles;

    public HealthRequest withBundles(Boolean bundles) {
        this.bundles = bundles;
        return this;
    }
    
    /**
     * Boolean parameter to account for plugin status in response.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=plugins")
    public Boolean plugins;

    public HealthRequest withPlugins(Boolean plugins) {
        this.plugins = plugins;
        return this;
    }
    
    /**
     * String parameter to exclude a plugin from status checks. Can be added multiple times. Does nothing if plugins is not true. This parameter is useful for special use cases where a plugin depends on the server being fully initialized before it can fully initialize itself.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=exclude-plugin")
    public String[] excludePlugin;

    public HealthRequest withExcludePlugin(String[] excludePlugin) {
        this.excludePlugin = excludePlugin;
        return this;
    }
    
    public HealthRequest(){}
}
