workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    openapi:
        inputs:
            - location: https://raw.githubusercontent.com/StyraInc/enterprise-opa/main/openapi/openapi.yaml
targets:
    opa:
        target: java
        source: openapi
        publish_java: true
        publish:
            java:
                ossrhUsername: c/WMQfyj
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
                useSonatypeLegacy: true
