workflowVersion: 1.0.0
sources:
    openapi:
        inputs:
            - location: https://raw.githubusercontent.com/StyraInc/enterprise-opa/main/openapi/openapi.yaml
targets:
    first-target:
        target: java
        source: openapi
