/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.openapi.models.errors;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.styra.opa.openapi.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.http.HttpResponse;
import java.util.Optional;

/**
 * ClientError - Bad Request
 */
public class ClientError extends RuntimeException {

    @JsonProperty("code")
    private String code;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("errors")
    private Optional<? extends java.util.List<Errors>> errors;

    @JsonProperty("message")
    private String message;

    @JsonCreator
    public ClientError(
            @JsonProperty("code") String code,
            @JsonProperty("errors") Optional<? extends java.util.List<Errors>> errors,
            @JsonProperty("message") String message) {
        Utils.checkNotNull(code, "code");
        Utils.checkNotNull(errors, "errors");
        Utils.checkNotNull(message, "message");
        this.code = code;
        this.errors = errors;
        this.message = message;
    }
    
    public ClientError(
            String code,
            String message) {
        this(code, Optional.empty(), message);
    }

    public String code(){
        return code;
    }

    public Optional<? extends java.util.List<Errors>> errors(){
        return errors;
    }

    public String message(){
        return message;
    }
    
    public final static Builder builder() {
        return new Builder();
    }

    public ClientError withCode(String code) {
        Utils.checkNotNull(code, "code");
        this.code = code;
        return this;
    }

    public ClientError withErrors(java.util.List<Errors> errors) {
        Utils.checkNotNull(errors, "errors");
        this.errors = Optional.ofNullable(errors);
        return this;
    }
    
    public ClientError withErrors(Optional<? extends java.util.List<Errors>> errors) {
        Utils.checkNotNull(errors, "errors");
        this.errors = errors;
        return this;
    }

    public ClientError withMessage(String message) {
        Utils.checkNotNull(message, "message");
        this.message = message;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ClientError other = (ClientError) o;
        return
            java.util.Objects.deepEquals(this.code, other.code) &&
            java.util.Objects.deepEquals(this.errors, other.errors) &&
            java.util.Objects.deepEquals(this.message, other.message);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            code,
            errors,
            message);
    }

    @Override
    public String toString() {
        return Utils.toString(ClientError.class,
                "code", code,
                "errors", errors,
                "message", message);
    }

    public final static class Builder {

        private String code;

        private Optional<? extends java.util.List<Errors>> errors = Optional.empty();

        private String message;

        private Builder() {
          // force use of static builder() method
        }

        public Builder code(String code) {
            Utils.checkNotNull(code, "code");
            this.code = code;
            return this;
        }

        public Builder errors(java.util.List<Errors> errors) {
            Utils.checkNotNull(errors, "errors");
            this.errors = Optional.ofNullable(errors);
            return this;
        }
        
        public Builder errors(Optional<? extends java.util.List<Errors>> errors) {
            Utils.checkNotNull(errors, "errors");
            this.errors = errors;
            return this;
        }

        public Builder message(String message) {
            Utils.checkNotNull(message, "message");
            this.message = message;
            return this;
        }

        public ClientError build() {
            return new ClientError(
                code,
                errors,
                message);
        }
    }
}
