/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.styra.opa.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.styra.opa.openapi.utils.Utils;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * CompileResultUCASTResult
 * 
 * <p>The partially evaluated result of the query as UCAST.
 */
public class CompileResultUCASTResult {

    /**
     * UCAST JSON object describing the conditions under which the query is true.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("query")
    private Optional<? extends Map<String, Object>> query;

    /**
     * Column masking rules, where the key is the column name, and the value describes which masking function to use.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("masks")
    private Optional<? extends Map<String, Map<String, MaskingRule>>> masks;

    @JsonIgnore
    private Map<String, Object> additionalProperties;

    @JsonCreator
    public CompileResultUCASTResult(
            @JsonProperty("query") Optional<? extends Map<String, Object>> query,
            @JsonProperty("masks") Optional<? extends Map<String, Map<String, MaskingRule>>> masks) {
        Utils.checkNotNull(query, "query");
        Utils.checkNotNull(masks, "masks");
        this.query = query;
        this.masks = masks;
        this.additionalProperties = new HashMap<>();
    }
    
    public CompileResultUCASTResult() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * UCAST JSON object describing the conditions under which the query is true.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, Object>> query() {
        return (Optional<Map<String, Object>>) query;
    }

    /**
     * Column masking rules, where the key is the column name, and the value describes which masking function to use.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, Map<String, MaskingRule>>> masks() {
        return (Optional<Map<String, Map<String, MaskingRule>>>) masks;
    }

    @JsonAnyGetter
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * UCAST JSON object describing the conditions under which the query is true.
     */
    public CompileResultUCASTResult withQuery(Map<String, Object> query) {
        Utils.checkNotNull(query, "query");
        this.query = Optional.ofNullable(query);
        return this;
    }

    /**
     * UCAST JSON object describing the conditions under which the query is true.
     */
    public CompileResultUCASTResult withQuery(Optional<? extends Map<String, Object>> query) {
        Utils.checkNotNull(query, "query");
        this.query = query;
        return this;
    }

    /**
     * Column masking rules, where the key is the column name, and the value describes which masking function to use.
     */
    public CompileResultUCASTResult withMasks(Map<String, Map<String, MaskingRule>> masks) {
        Utils.checkNotNull(masks, "masks");
        this.masks = Optional.ofNullable(masks);
        return this;
    }

    /**
     * Column masking rules, where the key is the column name, and the value describes which masking function to use.
     */
    public CompileResultUCASTResult withMasks(Optional<? extends Map<String, Map<String, MaskingRule>>> masks) {
        Utils.checkNotNull(masks, "masks");
        this.masks = masks;
        return this;
    }

    @JsonAnySetter
    public CompileResultUCASTResult withAdditionalProperty(String key, Object value) {
        // note that value can be null because of the way JsonAnySetter works
        Utils.checkNotNull(key, "key");
        additionalProperties.put(key, value); 
        return this;
    }    

    public CompileResultUCASTResult withAdditionalProperties(Map<String, Object> additionalProperties) {
        Utils.checkNotNull(additionalProperties, "additionalProperties");
        this.additionalProperties = additionalProperties;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompileResultUCASTResult other = (CompileResultUCASTResult) o;
        return 
            Objects.deepEquals(this.query, other.query) &&
            Objects.deepEquals(this.masks, other.masks) &&
            Objects.deepEquals(this.additionalProperties, other.additionalProperties);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            query,
            masks,
            additionalProperties);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CompileResultUCASTResult.class,
                "query", query,
                "masks", masks,
                "additionalProperties", additionalProperties);
    }
    
    public final static class Builder {
 
        private Optional<? extends Map<String, Object>> query = Optional.empty();
 
        private Optional<? extends Map<String, Map<String, MaskingRule>>> masks = Optional.empty();
 
        private Map<String, Object> additionalProperties = new HashMap<>();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * UCAST JSON object describing the conditions under which the query is true.
         */
        public Builder query(Map<String, Object> query) {
            Utils.checkNotNull(query, "query");
            this.query = Optional.ofNullable(query);
            return this;
        }

        /**
         * UCAST JSON object describing the conditions under which the query is true.
         */
        public Builder query(Optional<? extends Map<String, Object>> query) {
            Utils.checkNotNull(query, "query");
            this.query = query;
            return this;
        }

        /**
         * Column masking rules, where the key is the column name, and the value describes which masking function to use.
         */
        public Builder masks(Map<String, Map<String, MaskingRule>> masks) {
            Utils.checkNotNull(masks, "masks");
            this.masks = Optional.ofNullable(masks);
            return this;
        }

        /**
         * Column masking rules, where the key is the column name, and the value describes which masking function to use.
         */
        public Builder masks(Optional<? extends Map<String, Map<String, MaskingRule>>> masks) {
            Utils.checkNotNull(masks, "masks");
            this.masks = masks;
            return this;
        }

        public Builder additionalProperty(String key, Object value) {
            Utils.checkNotNull(key, "key");
            // we could be strict about null values (force the user
            // to pass `JsonNullable.of(null)`) but likely to be a bit 
            // annoying for additional properties building so we'll 
            // relax preconditions.
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            Utils.checkNotNull(additionalProperties, "additionalProperties");
            this.additionalProperties = additionalProperties;
            return this;
        }
        
        public CompileResultUCASTResult build() {
            return new CompileResultUCASTResult(
                query,
                masks)
                .withAdditionalProperties(additionalProperties);
        }
    }
}
