/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.styra.opa.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.styra.opa.openapi.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;

/**
 * CompileResultJSON
 * 
 * <p>The partially evaluated result of the query. Result will be empty if the query is never true.
 */
public class CompileResultJSON {

    /**
     * The partially evaluated result of the query.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("result")
    private Optional<? extends CompileResultJSONResult> result;

    @JsonCreator
    public CompileResultJSON(
            @JsonProperty("result") Optional<? extends CompileResultJSONResult> result) {
        Utils.checkNotNull(result, "result");
        this.result = result;
    }
    
    public CompileResultJSON() {
        this(Optional.empty());
    }

    /**
     * The partially evaluated result of the query.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<CompileResultJSONResult> result() {
        return (Optional<CompileResultJSONResult>) result;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * The partially evaluated result of the query.
     */
    public CompileResultJSON withResult(CompileResultJSONResult result) {
        Utils.checkNotNull(result, "result");
        this.result = Optional.ofNullable(result);
        return this;
    }

    /**
     * The partially evaluated result of the query.
     */
    public CompileResultJSON withResult(Optional<? extends CompileResultJSONResult> result) {
        Utils.checkNotNull(result, "result");
        this.result = result;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompileResultJSON other = (CompileResultJSON) o;
        return 
            Objects.deepEquals(this.result, other.result);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            result);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CompileResultJSON.class,
                "result", result);
    }
    
    public final static class Builder {
 
        private Optional<? extends CompileResultJSONResult> result = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The partially evaluated result of the query.
         */
        public Builder result(CompileResultJSONResult result) {
            Utils.checkNotNull(result, "result");
            this.result = Optional.ofNullable(result);
            return this;
        }

        /**
         * The partially evaluated result of the query.
         */
        public Builder result(Optional<? extends CompileResultJSONResult> result) {
            Utils.checkNotNull(result, "result");
            this.result = result;
            return this;
        }
        
        public CompileResultJSON build() {
            return new CompileResultJSON(
                result);
        }
    }
}
