/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.styra.opa.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.styra.opa.openapi.utils.Utils;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * CompileResultJSONResult
 * 
 * <p>The partially evaluated result of the query.
 */
public class CompileResultJSONResult {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("query")
    private Optional<? extends Query> query;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("support")
    private Optional<? extends Support> support;

    @JsonIgnore
    private Map<String, Object> additionalProperties;

    @JsonCreator
    public CompileResultJSONResult(
            @JsonProperty("query") Optional<? extends Query> query,
            @JsonProperty("support") Optional<? extends Support> support) {
        Utils.checkNotNull(query, "query");
        Utils.checkNotNull(support, "support");
        this.query = query;
        this.support = support;
        this.additionalProperties = new HashMap<>();
    }
    
    public CompileResultJSONResult() {
        this(Optional.empty(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Query> query() {
        return (Optional<Query>) query;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Support> support() {
        return (Optional<Support>) support;
    }

    @JsonAnyGetter
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public CompileResultJSONResult withQuery(Query query) {
        Utils.checkNotNull(query, "query");
        this.query = Optional.ofNullable(query);
        return this;
    }

    public CompileResultJSONResult withQuery(Optional<? extends Query> query) {
        Utils.checkNotNull(query, "query");
        this.query = query;
        return this;
    }

    public CompileResultJSONResult withSupport(Support support) {
        Utils.checkNotNull(support, "support");
        this.support = Optional.ofNullable(support);
        return this;
    }

    public CompileResultJSONResult withSupport(Optional<? extends Support> support) {
        Utils.checkNotNull(support, "support");
        this.support = support;
        return this;
    }

    @JsonAnySetter
    public CompileResultJSONResult withAdditionalProperty(String key, Object value) {
        // note that value can be null because of the way JsonAnySetter works
        Utils.checkNotNull(key, "key");
        additionalProperties.put(key, value); 
        return this;
    }    

    public CompileResultJSONResult withAdditionalProperties(Map<String, Object> additionalProperties) {
        Utils.checkNotNull(additionalProperties, "additionalProperties");
        this.additionalProperties = additionalProperties;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompileResultJSONResult other = (CompileResultJSONResult) o;
        return 
            Objects.deepEquals(this.query, other.query) &&
            Objects.deepEquals(this.support, other.support) &&
            Objects.deepEquals(this.additionalProperties, other.additionalProperties);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            query,
            support,
            additionalProperties);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CompileResultJSONResult.class,
                "query", query,
                "support", support,
                "additionalProperties", additionalProperties);
    }
    
    public final static class Builder {
 
        private Optional<? extends Query> query = Optional.empty();
 
        private Optional<? extends Support> support = Optional.empty();
 
        private Map<String, Object> additionalProperties = new HashMap<>();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder query(Query query) {
            Utils.checkNotNull(query, "query");
            this.query = Optional.ofNullable(query);
            return this;
        }

        public Builder query(Optional<? extends Query> query) {
            Utils.checkNotNull(query, "query");
            this.query = query;
            return this;
        }

        public Builder support(Support support) {
            Utils.checkNotNull(support, "support");
            this.support = Optional.ofNullable(support);
            return this;
        }

        public Builder support(Optional<? extends Support> support) {
            Utils.checkNotNull(support, "support");
            this.support = support;
            return this;
        }

        public Builder additionalProperty(String key, Object value) {
            Utils.checkNotNull(key, "key");
            // we could be strict about null values (force the user
            // to pass `JsonNullable.of(null)`) but likely to be a bit 
            // annoying for additional properties building so we'll 
            // relax preconditions.
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            Utils.checkNotNull(additionalProperties, "additionalProperties");
            this.additionalProperties = additionalProperties;
            return this;
        }
        
        public CompileResultJSONResult build() {
            return new CompileResultJSONResult(
                query,
                support)
                .withAdditionalProperties(additionalProperties);
        }
    }
}
