/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.styra.opa.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum GzipAcceptEncoding {
    GZIP("gzip");

    @JsonValue
    private final String value;

    private GzipAcceptEncoding(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
