/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.styra.opa.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum GzipContentEncoding {
    GZIP("gzip");

    @JsonValue
    private final String value;

    private GzipContentEncoding(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<GzipContentEncoding> fromValue(String value) {
        for (GzipContentEncoding o: GzipContentEncoding.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

