/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.styra.opa.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.styra.opa.openapi.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Provenance
 * 
 * <p>Provenance information can be requested on individual API calls and are returned inline with the API response. To obtain provenance information on an API call, specify the `provenance=true` query parameter when executing the API call.
 */
public class Provenance {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("version")
    private Optional<String> version;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("build_commit")
    private Optional<String> buildCommit;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("build_timestamp")
    private Optional<OffsetDateTime> buildTimestamp;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("build_host")
    private Optional<String> buildHost;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bundles")
    private Optional<? extends Map<String, Revision>> bundles;

    @JsonCreator
    public Provenance(
            @JsonProperty("version") Optional<String> version,
            @JsonProperty("build_commit") Optional<String> buildCommit,
            @JsonProperty("build_timestamp") Optional<OffsetDateTime> buildTimestamp,
            @JsonProperty("build_host") Optional<String> buildHost,
            @JsonProperty("bundles") Optional<? extends Map<String, Revision>> bundles) {
        Utils.checkNotNull(version, "version");
        Utils.checkNotNull(buildCommit, "buildCommit");
        Utils.checkNotNull(buildTimestamp, "buildTimestamp");
        Utils.checkNotNull(buildHost, "buildHost");
        Utils.checkNotNull(bundles, "bundles");
        this.version = version;
        this.buildCommit = buildCommit;
        this.buildTimestamp = buildTimestamp;
        this.buildHost = buildHost;
        this.bundles = bundles;
    }
    
    public Provenance() {
        this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
    }

    @JsonIgnore
    public Optional<String> version() {
        return version;
    }

    @JsonIgnore
    public Optional<String> buildCommit() {
        return buildCommit;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> buildTimestamp() {
        return buildTimestamp;
    }

    @JsonIgnore
    public Optional<String> buildHost() {
        return buildHost;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, Revision>> bundles() {
        return (Optional<Map<String, Revision>>) bundles;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public Provenance withVersion(String version) {
        Utils.checkNotNull(version, "version");
        this.version = Optional.ofNullable(version);
        return this;
    }

    public Provenance withVersion(Optional<String> version) {
        Utils.checkNotNull(version, "version");
        this.version = version;
        return this;
    }

    public Provenance withBuildCommit(String buildCommit) {
        Utils.checkNotNull(buildCommit, "buildCommit");
        this.buildCommit = Optional.ofNullable(buildCommit);
        return this;
    }

    public Provenance withBuildCommit(Optional<String> buildCommit) {
        Utils.checkNotNull(buildCommit, "buildCommit");
        this.buildCommit = buildCommit;
        return this;
    }

    public Provenance withBuildTimestamp(OffsetDateTime buildTimestamp) {
        Utils.checkNotNull(buildTimestamp, "buildTimestamp");
        this.buildTimestamp = Optional.ofNullable(buildTimestamp);
        return this;
    }

    public Provenance withBuildTimestamp(Optional<OffsetDateTime> buildTimestamp) {
        Utils.checkNotNull(buildTimestamp, "buildTimestamp");
        this.buildTimestamp = buildTimestamp;
        return this;
    }

    public Provenance withBuildHost(String buildHost) {
        Utils.checkNotNull(buildHost, "buildHost");
        this.buildHost = Optional.ofNullable(buildHost);
        return this;
    }

    public Provenance withBuildHost(Optional<String> buildHost) {
        Utils.checkNotNull(buildHost, "buildHost");
        this.buildHost = buildHost;
        return this;
    }

    public Provenance withBundles(Map<String, Revision> bundles) {
        Utils.checkNotNull(bundles, "bundles");
        this.bundles = Optional.ofNullable(bundles);
        return this;
    }

    public Provenance withBundles(Optional<? extends Map<String, Revision>> bundles) {
        Utils.checkNotNull(bundles, "bundles");
        this.bundles = bundles;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Provenance other = (Provenance) o;
        return 
            Objects.deepEquals(this.version, other.version) &&
            Objects.deepEquals(this.buildCommit, other.buildCommit) &&
            Objects.deepEquals(this.buildTimestamp, other.buildTimestamp) &&
            Objects.deepEquals(this.buildHost, other.buildHost) &&
            Objects.deepEquals(this.bundles, other.bundles);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            version,
            buildCommit,
            buildTimestamp,
            buildHost,
            bundles);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Provenance.class,
                "version", version,
                "buildCommit", buildCommit,
                "buildTimestamp", buildTimestamp,
                "buildHost", buildHost,
                "bundles", bundles);
    }
    
    public final static class Builder {
 
        private Optional<String> version = Optional.empty();
 
        private Optional<String> buildCommit = Optional.empty();
 
        private Optional<OffsetDateTime> buildTimestamp = Optional.empty();
 
        private Optional<String> buildHost = Optional.empty();
 
        private Optional<? extends Map<String, Revision>> bundles = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder version(String version) {
            Utils.checkNotNull(version, "version");
            this.version = Optional.ofNullable(version);
            return this;
        }

        public Builder version(Optional<String> version) {
            Utils.checkNotNull(version, "version");
            this.version = version;
            return this;
        }

        public Builder buildCommit(String buildCommit) {
            Utils.checkNotNull(buildCommit, "buildCommit");
            this.buildCommit = Optional.ofNullable(buildCommit);
            return this;
        }

        public Builder buildCommit(Optional<String> buildCommit) {
            Utils.checkNotNull(buildCommit, "buildCommit");
            this.buildCommit = buildCommit;
            return this;
        }

        public Builder buildTimestamp(OffsetDateTime buildTimestamp) {
            Utils.checkNotNull(buildTimestamp, "buildTimestamp");
            this.buildTimestamp = Optional.ofNullable(buildTimestamp);
            return this;
        }

        public Builder buildTimestamp(Optional<OffsetDateTime> buildTimestamp) {
            Utils.checkNotNull(buildTimestamp, "buildTimestamp");
            this.buildTimestamp = buildTimestamp;
            return this;
        }

        public Builder buildHost(String buildHost) {
            Utils.checkNotNull(buildHost, "buildHost");
            this.buildHost = Optional.ofNullable(buildHost);
            return this;
        }

        public Builder buildHost(Optional<String> buildHost) {
            Utils.checkNotNull(buildHost, "buildHost");
            this.buildHost = buildHost;
            return this;
        }

        public Builder bundles(Map<String, Revision> bundles) {
            Utils.checkNotNull(bundles, "bundles");
            this.bundles = Optional.ofNullable(bundles);
            return this;
        }

        public Builder bundles(Optional<? extends Map<String, Revision>> bundles) {
            Utils.checkNotNull(bundles, "bundles");
            this.bundles = bundles;
            return this;
        }
        
        public Provenance build() {
            return new Provenance(
                version,
                buildCommit,
                buildTimestamp,
                buildHost,
                bundles);
        }
    }
}
