/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.styra.opa.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum TargetDialects {
    UCAST_PLUS_ALL("ucast+all"),
    UCAST_PLUS_MINIMAL("ucast+minimal"),
    UCAST_PLUS_PRISMA("ucast+prisma"),
    UCAST_PLUS_LINQ("ucast+linq"),
    SQL_PLUS_SQLSERVER("sql+sqlserver"),
    SQL_PLUS_MYSQL("sql+mysql"),
    SQL_PLUS_POSTGRESQL("sql+postgresql"),
    SQL_PLUS_SQLITE("sql+sqlite");

    @JsonValue
    private final String value;

    private TargetDialects(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<TargetDialects> fromValue(String value) {
        for (TargetDialects o: TargetDialects.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

