/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.styra.opa.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.styra.opa.openapi.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

public class Ucast {

    /**
     * UCAST JSON object describing the conditions under which the query is true.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("query")
    private Optional<? extends CompileResultMultitargetQuery> query;

    /**
     * Column masking rules, where the first two nested keys represent the entity name and the property name, and the value describes which masking function to use.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("masks")
    private Optional<? extends Map<String, Map<String, MaskingRule>>> masks;

    @JsonCreator
    public Ucast(
            @JsonProperty("query") Optional<? extends CompileResultMultitargetQuery> query,
            @JsonProperty("masks") Optional<? extends Map<String, Map<String, MaskingRule>>> masks) {
        Utils.checkNotNull(query, "query");
        Utils.checkNotNull(masks, "masks");
        this.query = query;
        this.masks = masks;
    }
    
    public Ucast() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * UCAST JSON object describing the conditions under which the query is true.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<CompileResultMultitargetQuery> query() {
        return (Optional<CompileResultMultitargetQuery>) query;
    }

    /**
     * Column masking rules, where the first two nested keys represent the entity name and the property name, and the value describes which masking function to use.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, Map<String, MaskingRule>>> masks() {
        return (Optional<Map<String, Map<String, MaskingRule>>>) masks;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * UCAST JSON object describing the conditions under which the query is true.
     */
    public Ucast withQuery(CompileResultMultitargetQuery query) {
        Utils.checkNotNull(query, "query");
        this.query = Optional.ofNullable(query);
        return this;
    }

    /**
     * UCAST JSON object describing the conditions under which the query is true.
     */
    public Ucast withQuery(Optional<? extends CompileResultMultitargetQuery> query) {
        Utils.checkNotNull(query, "query");
        this.query = query;
        return this;
    }

    /**
     * Column masking rules, where the first two nested keys represent the entity name and the property name, and the value describes which masking function to use.
     */
    public Ucast withMasks(Map<String, Map<String, MaskingRule>> masks) {
        Utils.checkNotNull(masks, "masks");
        this.masks = Optional.ofNullable(masks);
        return this;
    }

    /**
     * Column masking rules, where the first two nested keys represent the entity name and the property name, and the value describes which masking function to use.
     */
    public Ucast withMasks(Optional<? extends Map<String, Map<String, MaskingRule>>> masks) {
        Utils.checkNotNull(masks, "masks");
        this.masks = masks;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Ucast other = (Ucast) o;
        return 
            Objects.deepEquals(this.query, other.query) &&
            Objects.deepEquals(this.masks, other.masks);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            query,
            masks);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Ucast.class,
                "query", query,
                "masks", masks);
    }
    
    public final static class Builder {
 
        private Optional<? extends CompileResultMultitargetQuery> query = Optional.empty();
 
        private Optional<? extends Map<String, Map<String, MaskingRule>>> masks = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * UCAST JSON object describing the conditions under which the query is true.
         */
        public Builder query(CompileResultMultitargetQuery query) {
            Utils.checkNotNull(query, "query");
            this.query = Optional.ofNullable(query);
            return this;
        }

        /**
         * UCAST JSON object describing the conditions under which the query is true.
         */
        public Builder query(Optional<? extends CompileResultMultitargetQuery> query) {
            Utils.checkNotNull(query, "query");
            this.query = query;
            return this;
        }

        /**
         * Column masking rules, where the first two nested keys represent the entity name and the property name, and the value describes which masking function to use.
         */
        public Builder masks(Map<String, Map<String, MaskingRule>> masks) {
            Utils.checkNotNull(masks, "masks");
            this.masks = Optional.ofNullable(masks);
            return this;
        }

        /**
         * Column masking rules, where the first two nested keys represent the entity name and the property name, and the value describes which masking function to use.
         */
        public Builder masks(Optional<? extends Map<String, Map<String, MaskingRule>>> masks) {
            Utils.checkNotNull(masks, "masks");
            this.masks = masks;
            return this;
        }
        
        public Ucast build() {
            return new Ucast(
                query,
                masks);
        }
    }
}
