/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.styra.opa.openapi.models.operations;

import com.styra.opa.openapi.utils.Utils;
import java.lang.Exception;

public class CompileQueryWithPartialEvaluationRequestBuilder {

    private CompileQueryWithPartialEvaluationRequest request;
    private final SDKMethodInterfaces.MethodCallCompileQueryWithPartialEvaluation sdk;

    public CompileQueryWithPartialEvaluationRequestBuilder(SDKMethodInterfaces.MethodCallCompileQueryWithPartialEvaluation sdk) {
        this.sdk = sdk;
    }

    public CompileQueryWithPartialEvaluationRequestBuilder request(CompileQueryWithPartialEvaluationRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompileQueryWithPartialEvaluationResponse call() throws Exception {

        return sdk.compileQueryWithPartialEvaluation(
            request);
    }
}
