/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.styra.opa.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.styra.opa.openapi.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.http.HttpResponse;
import java.util.Optional;

public class ExecutePolicyWithInputResponse implements com.styra.opa.openapi.utils.Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Success.
     * The server also returns 200 if the path refers to an undefined document. In this case, the response will not contain a result property.
     * 
     */
    private Optional<? extends com.styra.opa.openapi.models.shared.SuccessfulPolicyResponse> successfulPolicyResponse;

    private java.util.Map<String, java.util.List<String>> headers;

    @JsonCreator
    public ExecutePolicyWithInputResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends com.styra.opa.openapi.models.shared.SuccessfulPolicyResponse> successfulPolicyResponse,
            java.util.Map<String, java.util.List<String>> headers) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(successfulPolicyResponse, "successfulPolicyResponse");
        headers = Utils.emptyMapIfNull(headers);
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.successfulPolicyResponse = successfulPolicyResponse;
        this.headers = headers;
    }
    
    public ExecutePolicyWithInputResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            java.util.Map<String, java.util.List<String>> headers) {
        this(contentType, statusCode, rawResponse, Optional.empty(), headers);
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Success.
     * The server also returns 200 if the path refers to an undefined document. In this case, the response will not contain a result property.
     * 
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<com.styra.opa.openapi.models.shared.SuccessfulPolicyResponse> successfulPolicyResponse() {
        return (Optional<com.styra.opa.openapi.models.shared.SuccessfulPolicyResponse>) successfulPolicyResponse;
    }

    @JsonIgnore
    public java.util.Map<String, java.util.List<String>> headers() {
        return headers;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public ExecutePolicyWithInputResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public ExecutePolicyWithInputResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ExecutePolicyWithInputResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Success.
     * The server also returns 200 if the path refers to an undefined document. In this case, the response will not contain a result property.
     * 
     */
    public ExecutePolicyWithInputResponse withSuccessfulPolicyResponse(com.styra.opa.openapi.models.shared.SuccessfulPolicyResponse successfulPolicyResponse) {
        Utils.checkNotNull(successfulPolicyResponse, "successfulPolicyResponse");
        this.successfulPolicyResponse = Optional.ofNullable(successfulPolicyResponse);
        return this;
    }

    /**
     * Success.
     * The server also returns 200 if the path refers to an undefined document. In this case, the response will not contain a result property.
     * 
     */
    public ExecutePolicyWithInputResponse withSuccessfulPolicyResponse(Optional<? extends com.styra.opa.openapi.models.shared.SuccessfulPolicyResponse> successfulPolicyResponse) {
        Utils.checkNotNull(successfulPolicyResponse, "successfulPolicyResponse");
        this.successfulPolicyResponse = successfulPolicyResponse;
        return this;
    }

    public ExecutePolicyWithInputResponse withHeaders(java.util.Map<String, java.util.List<String>> headers) {
        Utils.checkNotNull(headers, "headers");
        this.headers = headers;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExecutePolicyWithInputResponse other = (ExecutePolicyWithInputResponse) o;
        return 
            java.util.Objects.deepEquals(this.contentType, other.contentType) &&
            java.util.Objects.deepEquals(this.statusCode, other.statusCode) &&
            java.util.Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            java.util.Objects.deepEquals(this.successfulPolicyResponse, other.successfulPolicyResponse) &&
            java.util.Objects.deepEquals(this.headers, other.headers);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            successfulPolicyResponse,
            headers);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ExecutePolicyWithInputResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "successfulPolicyResponse", successfulPolicyResponse,
                "headers", headers);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends com.styra.opa.openapi.models.shared.SuccessfulPolicyResponse> successfulPolicyResponse = Optional.empty();
 
        private java.util.Map<String, java.util.List<String>> headers;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Success.
         * The server also returns 200 if the path refers to an undefined document. In this case, the response will not contain a result property.
         * 
         */
        public Builder successfulPolicyResponse(com.styra.opa.openapi.models.shared.SuccessfulPolicyResponse successfulPolicyResponse) {
            Utils.checkNotNull(successfulPolicyResponse, "successfulPolicyResponse");
            this.successfulPolicyResponse = Optional.ofNullable(successfulPolicyResponse);
            return this;
        }

        /**
         * Success.
         * The server also returns 200 if the path refers to an undefined document. In this case, the response will not contain a result property.
         * 
         */
        public Builder successfulPolicyResponse(Optional<? extends com.styra.opa.openapi.models.shared.SuccessfulPolicyResponse> successfulPolicyResponse) {
            Utils.checkNotNull(successfulPolicyResponse, "successfulPolicyResponse");
            this.successfulPolicyResponse = successfulPolicyResponse;
            return this;
        }

        public Builder headers(java.util.Map<String, java.util.List<String>> headers) {
            Utils.checkNotNull(headers, "headers");
            this.headers = headers;
            return this;
        }
        
        public ExecutePolicyWithInputResponse build() {
            return new ExecutePolicyWithInputResponse(
                contentType,
                statusCode,
                rawResponse,
                successfulPolicyResponse,
                headers);
        }
    }
}

