/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.styra.opa.openapi.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
/**
 * ExecuteBatchPolicyWithInputRequestBody - The batch of inputs
 */

public class ExecuteBatchPolicyWithInputRequestBody {

    @JsonProperty("inputs")
    private java.util.Map<String, com.styra.opa.openapi.models.shared.Input> inputs;

    @JsonCreator
    public ExecuteBatchPolicyWithInputRequestBody(
            @JsonProperty("inputs") java.util.Map<String, com.styra.opa.openapi.models.shared.Input> inputs) {
        inputs = Utils.emptyMapIfNull(inputs);
        this.inputs = inputs;
    }

    @JsonIgnore
    public java.util.Map<String, com.styra.opa.openapi.models.shared.Input> inputs() {
        return inputs;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ExecuteBatchPolicyWithInputRequestBody withInputs(java.util.Map<String, com.styra.opa.openapi.models.shared.Input> inputs) {
        Utils.checkNotNull(inputs, "inputs");
        this.inputs = inputs;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExecuteBatchPolicyWithInputRequestBody other = (ExecuteBatchPolicyWithInputRequestBody) o;
        return 
            java.util.Objects.deepEquals(this.inputs, other.inputs);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            inputs);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ExecuteBatchPolicyWithInputRequestBody.class,
                "inputs", inputs);
    }
    
    public final static class Builder {
 
        private java.util.Map<String, com.styra.opa.openapi.models.shared.Input> inputs;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder inputs(java.util.Map<String, com.styra.opa.openapi.models.shared.Input> inputs) {
            Utils.checkNotNull(inputs, "inputs");
            this.inputs = inputs;
            return this;
        }
        
        public ExecuteBatchPolicyWithInputRequestBody build() {
            return new ExecuteBatchPolicyWithInputRequestBody(
                inputs);
        }
    }
}

