/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.styra.opa.openapi.models.operations;

import com.styra.opa.openapi.models.shared.GzipAcceptEncoding;
import com.styra.opa.openapi.models.shared.Input;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;

public class SDKMethodInterfaces {


    public interface MethodCallExecuteDefaultPolicyWithInput {
        com.styra.opa.openapi.models.operations.ExecuteDefaultPolicyWithInputResponse executeDefaultPolicyWithInput(
            Optional<Boolean> pretty,
            Optional<? extends GzipAcceptEncoding> acceptEncoding,
            Input input) throws Exception;
    }


    public interface MethodCallExecutePolicy {
        com.styra.opa.openapi.models.operations.ExecutePolicyResponse executePolicy(
            ExecutePolicyRequest request) throws Exception;
    }


    public interface MethodCallExecutePolicyWithInput {
        com.styra.opa.openapi.models.operations.ExecutePolicyWithInputResponse executePolicyWithInput(
            ExecutePolicyWithInputRequest request) throws Exception;
    }


    public interface MethodCallExecuteBatchPolicyWithInput {
        com.styra.opa.openapi.models.operations.ExecuteBatchPolicyWithInputResponse executeBatchPolicyWithInput(
            ExecuteBatchPolicyWithInputRequest request) throws Exception;
    }


    public interface MethodCallHealth {
        com.styra.opa.openapi.models.operations.HealthResponse health(
            Optional<Boolean> bundles,
            Optional<Boolean> plugins,
            Optional<? extends List<String>> excludePlugin) throws Exception;
    }


}
