/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.styra.opa.sdk.hooks;

//
// This file is written once by speakeasy code generation and 
// thereafter will not be overwritten by speakeasy updates. As a
// consequence any customization of this class will be preserved.
//

public final class SDKHooks {

    private SDKHooks() {
        // prevent instantiation
    }

    public static final void initialize(com.styra.opa.sdk.utils.Hooks hooks) {
        // register hooks here
        
        // for more information see
        // https://www.speakeasyapi.dev/docs/additional-features/sdk-hooks
    }
    
}
