name: Publish
"on":
  push:
    branches:
      - main
    paths:
      - RELEASES.md
      - '*/RELEASES.md'
jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
    with:
      create_release: true
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
