name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * *
jobs:
  generate:
    #uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    #with:
    #  force: ${{ github.event.inputs.force }}
    #  mode: pr
    #  speakeasy_version: latest
    #secrets:
    #  github_access_token: ${{ secrets.GITHUB_TOKEN }}
    #  speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
    #  slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Tune GitHub-hosted runner network
        uses: smorimoto/tune-github-hosted-runner-network@v1
      - uses: actions/checkout@v4
      - name: Run Generation Workflow
        uses: speakeasy-api/sdk-generation-action@v15
        with:
          speakeasy_version: latest
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          mode: pr
          force: ${{ github.event.inputs.force }}
          speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      - name: Change Repo Ownership
        run: |
          sudo chown -R runner ./repo
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Checkout PR and Apply Post-Generate Hook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd repo
          ref="$(git rev-parse --abbrev-ref HEAD)"
          cd ..
          mkdir -p ./liverepo
          cd liverepo
          gh pr checkout "$ref"
          ./scripts/post-generate-hook.sh
          if [ 0 -ge "$(git diff | wc -l)" ] ; then
            echo "no changes detected after fixup, nothing to commit"
            exit 0
          fi
          msg="post-generation for $ref at $(date)"
          git commit -m "$msg"
          git push origin "$ref"
