name: Publish
"on":
  push:
    branches:
      - main
    paths:
      - RELEASES.md
      - '*/RELEASES.md'
jobs:
  publish:
    name: Publish Java SDK
    runs-on: ubuntu-latest
    steps:
      - name: Tune GitHub-hosted runner network
        uses: smorimoto/tune-github-hosted-runner-network@v1
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"
          cache: "gradle"
      - name: Publish to Sonatype (legacy)
        run: |-
          pwd
          ./gradlew publish -x autoLintGradle --no-daemon
        env:
          MAVEN_USERNAME: ${{ secrets.ossrh_username }}
          MAVEN_PASSWORD: ${{ secrets.ossrh_password }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.java_gpg_secret_key }}
          ORG_GRADLE_PROJECT_signingPassphrase: ${{ secrets.java_gpg_passphrase }}
      - uses: ravsamhq/notify-slack-action@v2
        if: always() && env.SLACK_WEBHOOK_URL != ''
        with:
          status: ${{ job.status }}
          token: ${{ secrets.github_access_token }}
          notify_when: "failure"
          notification_title: "Failed to Publish Maven Central Release"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}> | <{run_url}|View Run>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  release:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Tune GitHub-hosted runner network
        uses: smorimoto/tune-github-hosted-runner-network@v1
      - id: release
        uses: speakeasy-api/sdk-generation-action@v15
        with:
          github_access_token: ${{ secrets.github_access_token }}
          action: "release"
          speakeasy_api_key: ${{ secrets.speakeasy_api_key }}
          speakeasy_server_url: ${{ inputs.speakeasy_server_url }}
      - uses: ravsamhq/notify-slack-action@v2
        if: always() && env.SLACK_WEBHOOK_URL != ''
        with:
          status: ${{ job.status }}
          token: ${{ secrets.github_access_token }}
          notify_when: "failure"
          notification_title: "Failed to create Github Release"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}> | <{run_url}|View Run>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

