name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * *
jobs:
  generate:
    #uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    #with:
    #  force: ${{ github.event.inputs.force }}
    #  mode: pr
    #  speakeasy_version: latest
    #secrets:
    #  github_access_token: ${{ secrets.GITHUB_TOKEN }}
    #  speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
    #  slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Tune GitHub-hosted runner network
        uses: smorimoto/tune-github-hosted-runner-network@v1
      - uses: actions/checkout@v4
      - name: Run Generation Workflow
        uses: speakeasy-api/sdk-generation-action@v15
        with:
          speakeasy_version: latest
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          mode: pr
          force: ${{ github.event.inputs.force }}
          speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      - name: Change Repo Ownership
        run: |
          sudo chown -R runner ./repo
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout "$(cd ./repo && git rev-parse --abbrev-ref HEAD)"
      #- name: Create Test Commit
      #  working-directory: ./repo
      #  run: |
      #    echo "this is a test $(date)" > test.txt
      #    git add test.txt
      #    git commit -m "add test file"
      #    git push origin "$(git rev-parse --abbrev-ref HEAD)"
      - run: |
          whoami
          pwd
          ls -lah
          for d in * ; do
            if [ -d "$d" ] ; then
              echo "===== $d"
              ls -lah "$d"
            fi
          done
        name: Record CWD and Listing
      - run: |
          git status
        name: Record Git Status
        working-directory: ./repo
      - run: |
          git log --format=oneline | head -n 10
        name: Record Recent Commits
        working-directory: ./repo

