name: Run unit tests and lint Java code
on:
  pull_request:

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew test lint checkstyleMain checkstyleTest
